import { IGardenGridItemProps } from "./elements/dashboardElements/GardenFruitGridItem";


// List of fruit data that uses IGardenGridItemProps
// Template:
// {
//     isSelected: false,
//     handleSelection: Function,
//     handleAddToMyGarden: Function,
//     name: "",
//     type: "",
//     image: "",
//     imageAlt: "",
//     description: "",
//     prerequisitesDescription: "",
//     extraDescription: "",
//     companionPlants: [],
//     commonTasks: [],
//     commonDiseases: [],
//     commonPests: [],
//     nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
//                     "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
//     },
//     tags: [],
//     nutrientSource: "",
// },
export const CONST_FRUIT_DATA: IGardenGridItemProps[] = [
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Apple",
        type: "Fruit",
        image: "Apple.png",
        imageAlt: "An apple.",
        description: "An apple is a round, edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. "
                     + "The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found.",
        prerequisitesDescription: "Apple seeds need cold stratification, a period of chilling, to germinate. Stratification will require cold storage at about 5°C, 40°F, for two to three months."
                                  + "The trees require full sun (at least 6 hours of direct sunlight each day), well draining soil (can tolerate sandy, loamy, and clay), and moderate amounts of water.",
        extraDescription: "Apples are often eaten raw. Cultivars bred for raw consumption are termed dessert or table apples.",
        companionPlants: ["Dill", "Fennel", "Nasturtiums", "Comfrey", "Chives", "Garlic", "Borage", "Yarrow", "Clover", "Marigold"],
        commonTasks: [
            "Keep soil PH slightly acidic, between 6.0 and 7.0", 
            "Regularly water, especially during dry periods but avoid overwatering as this can cause root rot",
            "Prune in late winter or early spring to remove dead, diseased, or broken branches before budding begins",
            "Fertilize in early spring before new growth begins - use a balanced fertilizer if desired",
            "Mulching aroudn the base can help retain moisture and prevent weeds - Use organic mulch such as wood chips, shredded leaves, or straw but avoid piling mulch against the trunk as this can cause rotting",
            "Harvest when the fruit is firm and fully colored - Twist the fruit upwards and give it a slight twist - If it comes off easily, it is ready to harvest",
            "Planting dill or fennel will attract beneficial insects that can help keep pests in check",
            "Planting nasturtiums, chives, marigolds, and garlic will help repel pests",
        ],
        commonDiseases: ["Apple scab", "Fire blight", "Cedar apple rust", "Powdery mildew", "Apple mosaic virus", "Apple stem grooving virus", "Apple chlorotic leaf spot virus"],
        commonPests: ["Codling moths", "Apple maggots", "Aphids", "Spider mites"],
        storingAndPreserving: "Apples can be stored in a cool (30-35°F) dry place with 90-95% relative humidity for up to 6-8 weeks. They can also be frozen, canned, or dried to "
                              + "retain them even longer. Do not store apples with other fruits or vegetables as they produce ethylene gas which can cause other produce to ripen too quickly.",
        nutritionDescription: "Apples are a good source of fiber and vitamin C. They also contain polyphenols, which may have numerous health benefits.",
        nutrients: { "Energy": 218, "Carbohydrates": 13.81, "Sugars": 10.39, "Dietary fiber": 2.4, "Fat": 0.17, "Protein": 0.26, "Vitamin A equiv": 0, "Vitamin B6": 3, "Vitamin C": 6, "Vitamin E": 1,
                        "Vitamin K": 2, "Calcium": 1, "Iron": 1, "Magnesium": 1, "Manganese": 2, "Phosphorus": 2, "Potassium": 2, "Sodium": 0, "Zinc": 0, "Folate": 0,
        },
        tags: ["Matures in 8 years", "Harvest in 2-5 years", "20-25FT Spread", "Cold Stratification"],
        nutrientSource: "https://fdc.nal.usda.gov/fdc-app.html#/food-details/1102644/nutrients",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Banana",
        type: "Fruit",
        image: "Banana.png",
        imageAlt: "A banana.",
        description: "A banana is an elongated, edible fruit - botanically a berry - produced by several kinds of large herbaceous flowering plants in the genus Musa.",
        prerequisitesDescription: "Bananas are tropical plants, so they prefer warm, humid climates. They are frost-sensitive and grow best in subtropical climates."
                                  + "Banana trees need full sun (at least 6 hours of direct sunlight per day), well draining soil, and moderate amounts of water deeply."
                                  + "As tropical plants, banana trees need high humidity to thrive.",
        extraDescription: `Worldwide, there is no sharp distinction between "bananas" and "plantains". Especially in the Americas and Europe, "banana" usually refers to soft, sweet, dessert bananas, particularly those of the Cavendish group, which are the main exports from banana-growing countries.`,
        companionPlants: ["Legumes", "Comfrey", "Ginger", "Turmeric", "Hibiscus"],
        commonTasks: [
            "Keep soil PH slightly acidic, between 5.5 and 6.5",
            "Regularly water, especially during dry periods but avoid overwatering as this can cause root rot",
            "Fertilize in early spring before new growth begins - use a balanced fertilizer if desired",
            "Prune the banana tree regularly as it grows to encourage new growth and fruit production",
            "Occasionally propagate new banana trees from the parent tree by removing and replanting the suckers that grow from the base of the tree",
        ],
        commonDiseases: ["Sigatoka", "Black leaf streak", "Banana wilt (Panama disease - Fusarium wilt)", "Moko disease", "Bunchy top"],
        commonPests: ["Nematodes", "Weevils", "Thrips", "Spider mites", "Aphids"],
        storingAndPreserving: "Bananas can be stored at room temperature for 5-7 days. They can also be frozen, canned, or dried to retain them even longer.",
        nutritionDescription: "Bananas are a good source of fiber, vitamin B6, and potassium. They also contain vitamin C, manganese, and magnesium.",
        nutrients: { "Energy": 371, "Carbohydrates": 22.84, "Sugars": 12.23, "Dietary fiber": 2.6, "Fat": 0.33, "Protein": 1.09, "Vitamin A equiv": 0, "Vitamin B6": 31, "Vitamin C": 10, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 2, "Magnesium": 8, "Manganese": 13, "Phosphorus": 3, "Potassium": 8, "Sodium": 0, "Zinc": 2, "Folate": 5,
        },
        tags: ["Matures in 1 year", "Harvest in 90-120 days", "12FT Spread", "Tropical"],
        nutrientSource: "https://en.wikipedia.org/wiki/Banana#Nutrition",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Tomato",
        type: "Fruit",
        image: "Tomato.png",
        imageAlt: "A tomato.",
        description: "The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as the tomato plant. The species originated in western South America, Mexico, and Central America.",
        prerequisitesDescription: "Tomatoes are warm-season plants and should be planted only after danger of frost has passed. In the Northeast, tomatoes are typically planted in late May or early June."
                                  + "Tomatoes need full sun (at least 6 hours of direct sunlight per day), well draining soil, and moderate amounts of water deeply."
                                  + "Tomatoes prefer loamy soil that has a neutral to slightly acidic pH. Ideal soil pH is between 6.0 and 6.8.",
        extraDescription: "While tomatoes are fruits—botanically classified as berries—they are commonly used culinarily as a vegetable ingredient or side dish.",
        companionPlants: ["Garlic", "Onions", "Lavender", "Basic", "Chives", "Asparagus", "Celery"],
        commonTasks: [
            "Keep soil PH slightly acidic, between 6.0 and 6.8",
            "Regularly water, especially during dry periods but avoid overwatering as this can cause root rot",
            "Add compost to the soil before planting to provide nutrients and improve soil quality",
            "Fertilize in early spring before new growth begins - use a balanced fertilizer if desired",
            "Keep fertilizer away from plant stems and leaves to avoid burning",
            "Provide support for the tomato plants to grow on as they mature via staking, trellising, or caging",
            "Prune the tomato plants regularly as they grow to encourage new growth and harvest yields",
            "To prune suckers, pinch them off with your fingers or use a sharp knife or pruning shears to cut them off at the base",
            "Harvest when the fruit is slightly firm and fully colored - Twist the fruit upwards and give it a slight twist - If it comes off easily, it is ready to harvest",
        ],
        commonDiseases: ["Septoria Leaf Spot", "Anthracnose", "Fusarium/Verticillium Wilt", "Early Blight", "Late Blight", "Mosaic Virus", "Blossom Drop", "Blossom End Rot", "Damping Off", "Sunscald"],
        commonPests: ["Spider mites", "Aphids", "Five-spotted hawk moth", "Whiteflies", "Flea beetles", "Corn earworm", "Hornworms", "Fruitworms", "Leaf-footed bugs", "Slugs/Snails", "Thrips"],
        storingAndPreserving: "Tomatoes can be stored in a refrigerator for about weeks. They can also be frozen, canned, or dried to retain them even longer.",
        nutritionDescription: "Tomatoes are a good source of vitamin C, potassium, folate, and vitamin K. They also contain lycopene, which may have numerous health benefits.",
        nutrients: { "Energy": 74, "Carbohydrates": 3.9, "Sugars": 2.6, "Dietary fiber": 1.2, "Fat": 0.2, "Protein": 0.9, "Vitamin A equiv": 5, "Vitamin B6": 6, "Vitamin C": 17, "Vitamin E": 4,
                        "Vitamin K": 8, "Calcium": 1, "Iron": 2, "Magnesium": 3, "Manganese": 5, "Phosphorus": 3, "Potassium": 5, "Sodium": 0, "Zinc": 2, "Folate": 4,
        },
        tags: ["Matures in 60-90 days", "Harvest in 7-14 days", "2FT Spread", "Warm Season", "pH 6.0-6.8"],
        nutrientSource: "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170457/nutrients",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Strawberry",
        type: "Fruit",
        image: "Strawberry.png",
        imageAlt: "A strawberry.",
        description: "The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit.",
        prerequisitesDescription: "Strawberries are perennials and will produce fruit for several years. They are grown from bare-root crowns planted in the spring."
                                  + "Make planting holes deep and wide enough to accommodate the entire root system without bending it. The crown should be at soil level, unburied."
                                  + "To settle their roots, water plants well at the time of planting. Note: It is also possible to grow strawberries from last year's runners."
                                  + "Practice crop rotation for strawberries. Do not plant in a site that recently had strawberries, tomatoes, peppers, or eggplant."
                                  + "Strawberries need full sun (at least 6 hours of direct sunlight per day), well draining soil, and moderate amounts of water deeply."
                                  + "Strawberries prefer loamy soil that has a neutral to slightly acidic pH. Ideal soil pH is between 5.5 and 6.5.",
        extraDescription: "Strawberries have a taste that varies by cultivar, and ranges from quite sweet to rather tart. Strawberries are an important commercial fruit crop, widely grown in all temperate regions of the world.",
        companionPlants: ["Asparagus", "Beans", "Peas", "Spinach", "Lettuce", "Garlic", "Horseradish", "Rhubarb"],
        commonTasks: [
            "Keep soil PH slightly acidic, between 5.5 and 6.5",
            "Regularly water, especially during dry periods but avoid overwatering as this can cause root rot",
            "Add compost to the soil before planting to provide nutrients and improve soil quality",
            "Fertilize in early spring before new growth begins - use a balanced fertilizer if desired",
            "Diligently weed the strawberry patch to prevent competition for nutrients and water",
            "(Winter) Mow/cut foliage down to one ince after growing season ends (late fall/early winter)",
            "(Winter) Mulch about 4 inches deep with straw, pine needles, or other organic material to protect the plants",
            "(Spring) Remove mulch after danger of frost has passed",
            "Harvest only fully red (ripe) berries, pick every 3 days, and cut by the stem and not the berry as you could damage the plant",
        ],
        commonDiseases: ["Angular leaf spot", "Anthracnose", "Leather rot", "Bortrytis fruit rot", "Fusarium/Verticillium wilt", "Leaf Blotch", "Powdery Mildew"],
        commonPests: ["Japanese beetles", "Slugs/Snails", "Spider mites", "Aphids", "Thrips", "Tarnished plant bug"],
        storingAndPreserving: "Strawberries can be stored in a refrigerator for about 3-7 days or frozen whole for about 2 months. They can also be frozen, canned, or dried to retain them even longer.",
        nutritionDescription: "Strawberries are a good source of vitamin C, manganese, folate, and potassium. They also contain antioxidants, which may have numerous health benefits.",
        nutrients: { "Energy": 136, "Carbohydrates": 7.68, "Sugars": 4.89, "Dietary fiber": 2, "Fat": 0.3, "Protein": 0.67, "Vitamin A equiv": 0, "Vitamin B6": 4, "Vitamin C": 71, "Vitamin E": 2,
                        "Vitamin K": 2, "Calcium": 2, "Iron": 3, "Magnesium": 4, "Manganese": 18, "Phosphorus": 3, "Potassium": 3, "Sodium": 0, "Zinc": 1, "Folate": 6,
        },
        tags: ["Matures in 60-90 days", "Harvest in 4-6 weeks", "1.5-2FT Spread", "Perennial"],
        nutrientSource: "https://fdc.nal.usda.gov/fdc-app.html#/food-details/747448/nutrients",
    },
];