import { IGardenGridItemProps } from "./elements/dashboardElements/GardenFruitGridItem";


// List of fruit data that uses IGardenGridItemProps
// Template:
// {
//     isSelected: false,
//     handleSelection: Function,
//     handleAddToMyGarden: Function,
//     name: "",
//     type: "",
//     image: "",
//     imageAlt: "",
//     description: "",
//     prerequisitesDescription: "",
//     extraDescription: "",
//     companionPlants: [],
//     commonTasks: [],
//     commonDiseases: [],
//     commonPests: [],
//     nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
//                     "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
//     },
//     tags: [],
//     nutrientSource: "",
// },
export const CONST_HERB_DATA: IGardenGridItemProps[] = [
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Basil",
        type: "Herb",
        image: "Basil.png",
        imageAlt: "Basil",
        description: "Basil, also called great basil, is a culinary herb of the family Lamiaceae (mints). Basil is native to tropical regions from central Africa to Southeast Asia. It is a tender plant, and is used in cuisines worldwide.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 94, "Carbohydrates": 2.65, "Sugars": 0.3, "Dietary fiber": 1.6, "Fat": 0.64, "Protein": 3.15, "Vitamin A equiv": 264, "Vitamin B6": 12, "Vitamin C": 22, "Vitamin E": 5,
                        "Vitamin K": 395, "Calcium": 18, "Iron": 24, "Magnesium": 18, "Manganese": 55, "Phosphorus": 8, "Potassium": 6, "Sodium": 0, "Zinc": 9, "Folate": 0,
        },
        tags: ["3-4in Spread (young)", "12in Spread (adult)",],
        nutrientSource: "https://en.wikipedia.org/wiki/Basil",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Cilantro",
        type: "Herb",
        image: "Cilantro.png",
        imageAlt: "Cilantro",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Dill",
        type: "Herb",
        image: "Dill.png",
        imageAlt: "Dill",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Mint",
        type: "Herb",
        image: "Mint.png",
        imageAlt: "Mint",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Oregano",
        type: "Herb",
        image: "Oregano.png",
        imageAlt: "Oregano",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Parsley",
        type: "Herb",
        image: "Parsley.png",
        imageAlt: "Parsley",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Rosemary",
        type: "Herb",
        image: "Rosemary.png",
        imageAlt: "Rosemary",
        description: "Rosemary is a woody, perennial herb with fragrant, evergreen, needle-like leaves and white, pink, purple, or blue flowers, native to the Mediterranean region. It is a member of the mint family Lamiaceae, which includes many other herbs.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "https://en.wikipedia.org/wiki/Rosemary",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Sage",
        type: "Herb",
        image: "Sage.png",
        imageAlt: "Sage",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Thyme",
        type: "Herb",
        image: "Thyme.png",
        imageAlt: "Thyme",
        description: "",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
];