import { IGardenGridItemProps } from "./elements/dashboardElements/GardenFruitGridItem";


// List of fruit data that uses IGardenGridItemProps
// Template:
// {
//     isSelected: false,
//     handleSelection: Function,
//     handleAddToMyGarden: Function,
//     name: "",
//     type: "",
//     image: "",
//     imageAlt: "",
//     description: "",
//     prerequisitesDescription: "",
//     extraDescription: "",
//     companionPlants: [],
//     commonTasks: [],
//     commonDiseases: [],
//     commonPests: [],
//     nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
//                     "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
//     },
//     tags: [],
//     nutrientSource: "",
// },
export const CONST_VEGETABLE_DATA: IGardenGridItemProps[] = [
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Asparagus",
        type: "Vegetable",
        image: "Asparagus.png",
        imageAlt: "Asparagus",
        description: "Asparagus, or garden asparagus, folk name sparrow grass, scientific name Asparagus officinalis, is a perennial flowering plant species in the genus Asparagus. Its young shoots are used as a spring vegetable.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Broccoli",
        type: "Vegetable",
        image: "Broccoli.png",
        imageAlt: "Broccoli",
        description: "Broccoli is an edible green plant in the cabbage family whose large flowering head, stalk and small associated leaves are eaten as a vegetable. Broccoli is classified in the Italica cultivar group of the species Brassica oleracea.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Green Beans",
        type: "Vegetable",
        image: "GreenBeans.png",
        imageAlt: "Green Beans",
        description: "Green beans are the unripe, young fruit and protective pods of various cultivars of the common bean. Immature or young pods of the runner bean, yardlong bean, and hyacinth bean are used in a similar way.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Brussels Sprouts",
        type: "Vegetable",
        image: "BrusselsSprouts.png",
        imageAlt: "Brussels Sprouts",
        description: "Brussels sprouts are a member of the Gemmifera Group of cabbages, grown for its edible buds. The leafy green vegetables are typically 2.5–4 cm in diameter and look like miniature cabbages. The Brussels sprout has long been popular in Brussels, Belgium, and may have originated and gained its name there.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Green Cabbage",
        type: "Vegetable",
        image: "GreenCabbage.png",
        imageAlt: "Green Cabbage",
        description: "Green cabbage, also known as white cabbage, is a cultivar of cabbage, Brassica oleracea capitata, grown for its edible head. Green cabbage is a multi-layered vegetable. It has an outer layer of dark green leaves and an inner layer of light green leaves. It is generally round in shape and can be easily identified by its smooth texture and appearance. It is a member of the Brassica family and is closely related to broccoli, cauliflower, and Brussels sprouts.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Sweet Peppers",
        type: "Vegetable",
        image: "SweetPeppers.png",  
        imageAlt: "Sweet Peppers",
        description: "Sweet peppers are a cultivar group of the species Capsicum annuum. Cultivars of the plant produce fruits in different colors, including red, yellow, orange, green, white, and purple. Bell peppers are sometimes grouped with less pungent pepper varieties as sweet peppers. Peppers are native to Mexico, Central America, and northern South America. Pepper seeds were imported to Spain in 1493, and from there, spread to other European, African, and Asian countries. Today, China is the world's largest pepper producer, followed by Mexico and Indonesia.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Carrots",
        type: "Vegetable",
        image: "Carrots.png",
        imageAlt: "Carrots",
        description: "Carrot is a root vegetable, usually orange in color, though purple, black, red, white, and yellow cultivars exist. They are a domesticated form of the wild carrot, Daucus carota, native to Europe and Southwestern Asia. The plant probably originated in Persia and was originally cultivated for its leaves and seeds. The most commonly eaten part of the plant is the taproot, although the stems and leaves are eaten as well. The domestic carrot has been selectively bred for its greatly enlarged, more palatable, less woody-textured taproot.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Cauliflower",
        type: "Vegetable",
        image: "Cauliflower.png",
        imageAlt: "Cauliflower",
        description: "Caulliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae family. It is an annual plant that reproduces by seed. Typically, only the head is eaten – the edible white flesh sometimes called curd. The cauliflower head is composed of a white inflorescence meristem. Cauliflower heads resemble those in broccoli, which differs in having flower buds as the edible portion. Brassica oleracea also includes broccoli, brussels sprouts, cabbage, collard greens, and kale, collectively called cole crops, though they are of different cultivar groups.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Celery",
        type: "Vegetable",
        image: "Celery.png",
        imageAlt: "Celery",
        description: "Celery is a marshland plant in the family Apiaceae that has been cultivated as a vegetable since antiquity. Celery has a long fibrous stalk tapering into leaves. Depending on location and cultivar, either its stalks, leaves or hypocotyl are eaten and used in cooking. Celery seed is also used as a spice and its extracts have been used in herbal medicine.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Cucumber",
        type: "Vegetable",
        image: "Cucumber.png",
        imageAlt: "Cucomber",
        description: "Cucomber is a widely cultivated plant in the gourd family, Cucurbitaceae. It is a creeping vine that bears cucumiform fruits that are used as vegetables. There are three main varieties of cucumber: slicing, pickling, and seedless. Within these varieties, several cultivars have been created. In North America, the term wild cucumber refers to plants in the genera Echinocystis and Marah, but these are not closely related. The cucumber is originally from South Asia, but now grows on most continents. Many different types of cucumber are traded on the global market.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Eggplant",
        type: "Vegetable",
        image: "Eggplant.png",
        imageAlt: "Eggplant",
        description: "Eggplant, aubergine or brinjal is a plant species in the nightshade family Solanaceae. Solanum melongena is grown worldwide for its edible fruit. Most commonly purple, the spongy, absorbent fruit is used in several cuisines. Typically used as a vegetable in cooking, it is a berry by botanical definition. As a member of the genus Solanum, it is related to tomato and potato. Like the tomato, its skin and seeds can be eaten, but, like the potato, it is usually eaten cooked. Eggplant is nutritionally low in macronutrient and micronutrient content, but the capability of the fruit to absorb oils and flavors into its flesh through cooking expands its use in the culinary arts.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Fennel",
        type: "Vegetable",
        image: "Fennel.png",
        imageAlt: "Fennel",
        description: "Fennel is a flowering plant species in the carrot family. It is a hardy, perennial herb with yellow flowers and feathery leaves. It is indigenous to the shores of the Mediterranean but has become widely naturalized in many parts of the world, especially on dry soils near the sea-coast and on riverbanks.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Garlic",
        type: "Vegetable",
        image: "Garlic.png",
        imageAlt: "Garlic",
        description: "Garlic is a species in the onion genus, Allium. Its close relatives include the onion, shallot, leek, chive, Welsh onion and Chinese onion. It is native to Central Asia and northeastern Iran and has long been a common seasoning worldwide, with a history of several thousand years of human consumption and use. It was known to ancient Egyptians and has been used as both a food flavoring and a traditional medicine. China produces some 80% of the world's supply of garlic.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Ginger",
        type: "Vegetable",
        image: "Ginger.png",
        imageAlt: "Ginger",
        description: "Ginger is a flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine. It is a herbaceous perennial which grows annual pseudostems about one meter tall bearing narrow leaf blades. The inflorescences bear pale yellow with purple flowers and arise directly from the rhizome on separate shoots.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Kale",
        type: "Vegetable",
        image: "Kale.png",
        imageAlt: "Kale",
        description: "Kale or leaf cabbage is one of certain cultivars of cabbage grown for their edible leaves, although some are used as ornamentals. Kale plants have green or purple leaves, and the central leaves do not form a head. Kales are considered to be closer to wild cabbage than most domesticated forms of Brassica oleracea.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Leeks",
        type: "Vegetable",
        image: "Leeks.png",
        imageAlt: "Leeks",
        description: "Leek is a vegetable, a cultivar of Allium ampeloprasum, the broadleaf wild leek. The edible part of the plant is a bundle of leaf sheaths that is sometimes erroneously called a stem or stalk. The genus Allium also contains the onion, garlic, shallot, scallion, chive, and Chinese onion. Historically, many scientific names were used for leeks, but they are now all treated as cultivars of A. ampeloprasum. The name 'leek' developed from the Anglo-Saxon word leac.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Iceberg Lettuce",
        type: "Vegetable",
        image: "IcebergLettuce.png",
        imageAlt: "Iceberg Lettuce",
        description: "Iceberg lettuce is a variety of lettuce with crisp leaves which grows in a spherical head resembling a cabbage. It is a cultivar of what is commonly known as cabbage lettuce. It is mostly grown as a leaf vegetable, but sometimes for its stem and seeds. Other common names include cabbage lettuce, garden lettuce, or crisphead lettuce.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Watermelon",
        type: "Vegetable",
        image: "Watermelon.png",
        imageAlt: "Watermelon",
        description: "Watermelon is a flowering plant species of the Cucurbitaceae family. A scrambling and trailing vine-like plant, it was originally domesticated in Africa. It is a highly cultivated fruit worldwide, with more than 1,000 varieties. Wild watermelon seeds have been found in the prehistoric Libyan site of Uan Muhuggiag. Watermelon is grown in tropical and subtropical areas worldwide for its large edible fruit, also known as a watermelon, which is a special kind of berry with a hard rind and no internal division, botanically called a pepo. The sweet, juicy flesh is usually deep red to pink, with many black seeds, although seedless varieties have been cultivated. The fruit can be eaten raw or pickled and the rind is edible after cooking. It is commonly consumed as a juice or as an ingredient in mixed beverages.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Honeydew Melon",
        type: "Vegetable",
        image: "HoneydewMelon.png",
        imageAlt: "Honeydew Melon",
        description: "Honeydew, also known as white antibes, is a cultivar group of the muskmelon, Cucumis melo in the gourd family. The Inodorus group includes honeydew, crenshaw, casaba, winter, and other mixed melons. A honeydew has a round to slightly oval shape, typically 15–22 cm long. It generally ranges in weight from 1.8 to 3.6 kg. The flesh is usually pale green in color, while the smooth peel ranges from greenish to yellow. Like most fruit, honeydew has seeds. Honeydew's thick, juicy, sweet flesh is often eaten for dessert, and is commonly found in supermarkets across the world. This fruit grows best in semiarid climates and is harvested based on maturity, not size. Maturity can be hard to judge, but is based upon ground color ranging from greenish white (immature) to creamy yellow (mature). Quality is also determined by the honeydew having a nearly spherical shape with a surface free of scars or defects.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Shiitake Mushrooms",
        type: "Vegetable",
        image: "ShiitakeMushrooms.png",
        imageAlt: "Shiitake Mushrooms",
        description: "Shiitake is an edible mushroom native to East Asia, which is cultivated and consumed in many Asian countries. It is considered a medicinal mushroom in some forms of traditional medicine. The fungus was first described scientifically as Agaricus edodes by Miles Joseph Berkeley in 1877. It was placed in the genus Lentinula by David Pegler in 1976. The fungus has acquired an extensive synonymy in its taxonomic history: Agaricus edodes Berk. 1877, Cortinellus edodes (Berk.) S.Ito & S.Imai 1938, Lentinus edodes (Berk.) Singer 1943, Lentinus shiitake Joss. 1943, and Lentinus tonkinensis Pat. 1907. The name Lentinula edodes has been proposed as a substitute for the original name. Shiitake grow in groups on the decaying wood of deciduous trees, particularly shii, chestnut, oak, maple, beech, sweetgum, poplar, hornbeam, ironwood, mulberry, and chinquapin. Its natural distribution includes warm and moist climates in southeast Asia.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Portobello Mushrooms",
        type: "Vegetable",
        image: "PortobelloMushrooms.png",
        imageAlt: "Portobello Mushrooms",
        description: "Portobello mushrooms are mature cremini mushrooms that have grown to a large size. They are known for their dark brown color and their large, flat caps. Portobello mushrooms are a type of edible mushroom that is native to the grasslands of Europe and North America. They are a type of agaricus bisporus, the same species as the common white button mushroom. Portobello mushrooms are a type of edible mushroom that is native to the grasslands of Europe and North America. They are a type of agaricus bisporus, the same species as the common white button mushroom. Portobello mushrooms are a type of edible mushroom that is native to the grasslands of Europe and North America. They are a type of agaricus bisporus, the same species as the common white button mushroom. Portobello mushrooms are a type of edible mushroom that is native to the grasslands of Europe and North America. They are a type of agaricus bisporus, the same species as the common white button mushroom.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Onion - Red",
        type: "Vegetable",
        image: "OnionRed.png",
        imageAlt: "Onion - Red",
        description: "Red onions, are cultivars of the onion with purplish red skin and white flesh tinged with red. These onions tend to be medium to large in size and have a mild to sweet flavor. They are often consumed raw, grilled or lightly cooked with other foods, or added as a decoration to salads. They tend to lose their redness when cooked. Red onions are available throughout the year. The red color comes from anthocyanidins such as cyanidin. Red onions are high in flavonoids. They can be stored 3 to 4 months at room temperature. Red onions are most often used in salads, salsas, and other raw preparations for their color and relatively mild flavor. The lovely red color becomes washed out during cooking. Red onions are available throughout the year. The red color comes from anthocyanidins such as cyanidin. Red onions are high in flavonoids. They can be stored 3 to 4 months at room temperature. Red onions are most often used in salads, salsas, and other raw preparations for their color and relatively mild flavor. The lovely red color becomes washed out during cooking.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Onion - White",
        type: "Vegetable",
        image: "OnionWhite.png",
        imageAlt: "Onion - White",
        description: "White onions are cultivars of the onion with white bulbs and white flesh. They are typically available throughout the year. White onions tend to have a sharper and more pungent flavor than yellow onions. They have a slightly shorter shelf life than yellow or red onions. White onions are typically used in white sauces, potato and pasta salads, and in Mexican or Southwestern cuisine. They can be sauteed to a dark brown color and served to provide a sweet and sour flavor to other foods. White onions are typically used in white sauces, potato and pasta salads, and in Mexican or Southwestern cuisine. They can be sauteed to a dark brown color and served to provide a sweet and sour flavor to other foods. White onions are typically used in white sauces, potato and pasta salads, and in Mexican or Southwestern cuisine. They can be sauteed to a dark brown color and served to provide a sweet and sour flavor to other foods. White onions are typically used in white sauces, potato and pasta salads, and in Mexican or Southwestern cuisine. They can be sauteed to a dark brown color and served to provide a sweet and sour flavor to other foods.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Shallots",
        type: "Vegetable",
        image: "Shallots.png",
        imageAlt: "Shallots",
        description: "Shallots are a type of onion, specifically a botanical variety of the species Allium cepa. The shallot was formerly classified as a separate species, A. ascalonicum, a name now considered a synonym of the currently accepted name. Its close relatives include the garlic, leek, chive, and Chinese onion. Shallots probably originated in Central or Southwest Asia, travelling from there to India and the eastern Mediterranean. The name shallot comes from Ashkelon, an ancient Canaanite city, where people in classical Greek times believed shallots originated.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Parsnips",
        type: "Vegetable",
        image: "Parsnips.png",
        imageAlt: "Parsnips",
        description: "Parsnip is a root vegetable closely related to carrot and parsley; all belong to the family Apiaceae. It is a biennial plant usually grown as an annual. Its long, tuberous root has cream-colored skin and flesh, and, left in the ground to mature, it becomes sweeter in flavor after winter frosts. In its first growing season, the plant has a rosette of pinnate, mid-green leaves. If unharvested, it produces its flowering stem, topped by an umbel of yellow flowers, in its second growing season. By this time, the stem is woody and the tuber is inedible. The seeds are pale brown, flat, and winged.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Peas",
        type: "Vegetable",
        image: "Peas.png",
        imageAlt: "Peas",
        description: "Peas are contained within a pod. Pea pods are botanically fruit, since they contain seeds and develop from the ovary of a (pea) flower. It is a cool-season crop grown in many parts of the world; planting can take place from winter to early summer depending on location. The average pea weighs between 0.1 and 0.36 grams. The immature peas are used as a vegetable, fresh, frozen or canned; varieties of the species typically called field peas are grown to produce dry peas like the split pea shelled from the matured pod. These are the basis of pease porridge and pea soup, staples of medieval cuisine; in Europe, consuming fresh immature green peas was an innovation of Early Modern cuisine.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },{
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Potatoes - Russet",
        type: "Vegetable",
        image: "PotatoesRusset.png",
        imageAlt: "Russet Potatoes",
        description: "Russet potatoes are large, starchy potatoes with a high dry matter content. They are characterized by a rough, netted, brown skin and white flesh. They are typically oblong in shape. Russet potatoes are the most widely grown potatoes in North America. They are available year-round. Russet potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Russet potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Russet potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Russet potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Russet potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Potatoes - Gold",
        type: "Vegetable",
        image: "PotatoesGold.png",
        imageAlt: "Gold Potatoes",
        description: "Golden potatoes are medium-sized potatoes with a smooth, thin, light tan skin and yellow flesh. They are available year-round. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips. Golden potatoes are typically used for baking, mashing and french fries. They are also used for hash browns, potato pancakes and potato chips.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Radishes",
        type: "Vegetable",
        image: "Radishes.png",
        imageAlt: "Radishes",
        description: "Radishes are edible root vegetables in the Brassicaceae family that are grown and consumed throughout the world, being mostly eaten raw as a crunchy salad vegetable with a pungent flavor. There are numerous varieties, varying in size, flavor, color, and length of time they take to mature. Radishes owe their sharp flavor to the various chemical compounds produced by the plants, including glucosinolate, myrosinase, and isothiocyanate. They are sometimes grown as companion plants and suffer from few pests and diseases. They germinate quickly and grow rapidly, smaller varieties being ready for consumption within a month, while larger daikon varieties take several months. Another use of radish is as cover or catch crop in winter or as a forage crop. Some radishes are grown for their seeds; daikon, for instance, may be grown for oil production. Others are used for sprouting and both roots and leaves are sometimes served cooked.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Rhubarb",
        type: "Vegetable",
        image: "Rhubarb.png",
        imageAlt: "Rhubarb",
        description: "Rhubarb is a cultivated plant in the genus Rheum in the family Polygonaceae. It is a herbaceous perennial growing from short, thick rhizomes. Historically, different plants have been called rhubarb in English. The fleshy, edible stalks of other species and hybrids were cooked and used for food. The large, triangular leaves contain high levels of oxalic acid and anthrone glycosides, making them inedible. The small flowers are grouped in large compound leafy greenish-white to rose-red inflorescences. The precise origin of culinary rhubarb is unknown. The species Rheum rhabarbarum (syn. R. undulatum) and R. rhaponticum were grown in Europe before the 18th century and used for medicinal purposes. By the early 18th century, these two species and a possible hybrid of unknown origin, R. x hybridum, were grown as vegetable crops in England and Scandinavia. They readily hybridize, so botanical authorities differ on the number of species.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Spinach",
        type: "Vegetable",
        image: "Spinach.png",
        imageAlt: "Spinach",
        description: "Spinach is an edible flowering plant in the family Amaranthaceae native to central and western Asia. Its leaves are commonly eaten as a vegetable, either fresh, frozen, canned, chipped, or dehydrated. It may be eaten cooked or raw, and the taste differs considerably; the high oxalate content may be reduced by steaming. The leaves are alternate, simple, ovate to triangular, and very variable in size: 2–30 cm (1–12 in) long and 1–15 cm (0.4–5.9 in) broad, with larger leaves at the base of the plant and small leaves higher on the flowering stem. The flowers are inconspicuous, yellow-green, 3–4 mm (0.1–0.2 in) in diameter, maturing into a small, hard, dry, lumpy fruit cluster 5–10 mm (0.2–0.4 in) across containing several seeds.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Sweet Corn",
        type: "Vegetable",
        image: "SweetCorn.png",
        imageAlt: "Sweet Corn",
        description: "Sweet corn is a variety of maize with a high sugar content. Sweet corn is the result of a naturally occurring recessive mutation in the genes which control conversion of sugar to starch inside the endosperm of the corn kernel. Unlike field corn varieties, which are harvested when the kernels are dry and mature (dent stage), sweet corn is picked when immature (milk stage) and prepared and eaten as a vegetable, rather than a grain. Since the process of maturation involves converting sugar to starch, sweet corn stores poorly and must be eaten fresh, canned, or frozen, before the kernels become tough and starchy. Sweet corn occurs as a spontaneous mutation in field corn and was grown by several Native American tribes. The Iroquois gave the first recorded sweet corn (called 'Papoon') to European settlers in 1779. It soon became a popular food in southern and central regions of the United States.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
    {
        isSelected: false,
        handleSelection: Function,
        handleAddToMyGarden: Function,
        name: "Turmeric",
        type: "Vegetable",
        image: "Turmeric.png",
        imageAlt: "Turmeric",
        description: "Turmeric is a flowering plant, Curcuma longa of the ginger family, Zingiberaceae, the roots of which are used in cooking. The plant is a perennial, rhizomatous, herbaceous plant native to the Indian subcontinent and Southeast Asia, that requires temperatures between 20 and 30 °C (68 and 86 °F) and a considerable amount of annual rainfall to thrive. Plants are gathered annually for their rhizomes, and propagated from some of those rhizomes in the following season. When not used fresh, the rhizomes are boiled for about 30–45 minutes then dried in hot ovens, after which they are ground into a deep-orange-yellow powder commonly used as a coloring and flavoring agent in many Asian cuisines, especially for curries, as well as for dyeing. Turmeric powder has a warm, bitter, black pepper-like flavor and earthy, mustard-like aroma. Although long used in Ayurvedic medicine to treat various diseases, there is little high-quality clinical evidence for use of turmeric or its main constituent, curcumin, as a therapy.",
        prerequisitesDescription: "",
        extraDescription: "",
        companionPlants: [],
        commonTasks: [],
        commonDiseases: [],
        commonPests: [],
        nutrients: { "Energy": 0, "Carbohydrates": 0, "Sugars": 0, "Dietary fiber": 0, "Fat": 0, "Protein": 0, "Vitamin A equiv": 0, "Vitamin B6": 0, "Vitamin C": 0, "Vitamin E": 0,
                        "Vitamin K": 0, "Calcium": 0, "Iron": 0, "Magnesium": 0, "Manganese": 0, "Phosphorus": 0, "Potassium": 0, "Sodium": 0, "Zinc": 0, Folate: 0,
        },
        tags: [],
        nutrientSource: "",
    },
]